---
# -- See the common values.yaml for all the options you can set.
# https://github.com/bjw-s/helm-charts/blob/common-2.5.0/charts/library/common/values.yaml
global:
  fullnameOverride:

image:
  repository: public.ecr.aws/n4e0e1y0/beam-blobcache-v2
  tag: latest

controllers:
  main:
    annotations: {}
    labels: {}
    replicas: 1
    strategy: Recreate # Can be Recreate or RollingUpdate
    rollingUpdate:
      unavailable:
      surge:
    containers:
      main:
        resources:
          limits: {}
          requests: {}