apiVersion: v1
kind: Service
metadata:
  name: blobcache
  namespace: beta9
spec:
  selector:
    app: blobcache
  ports:
    - name: grpc
      protocol: TCP
      port: 2049
      targetPort: 2049
  type: ClusterIP