// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.25.1
// source: blobcache.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	BlobCache_GetContent_FullMethodName   = "/blobcache.BlobCache/GetContent"
	BlobCache_StoreContent_FullMethodName = "/blobcache.BlobCache/StoreContent"
)

// BlobCacheClient is the client API for BlobCache service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BlobCacheClient interface {
	GetContent(ctx context.Context, in *GetContentRequest, opts ...grpc.CallOption) (*GetContentResponse, error)
	StoreContent(ctx context.Context, opts ...grpc.CallOption) (BlobCache_StoreContentClient, error)
}

type blobCacheClient struct {
	cc grpc.ClientConnInterface
}

func NewBlobCacheClient(cc grpc.ClientConnInterface) BlobCacheClient {
	return &blobCacheClient{cc}
}

func (c *blobCacheClient) GetContent(ctx context.Context, in *GetContentRequest, opts ...grpc.CallOption) (*GetContentResponse, error) {
	out := new(GetContentResponse)
	err := c.cc.Invoke(ctx, BlobCache_GetContent_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *blobCacheClient) StoreContent(ctx context.Context, opts ...grpc.CallOption) (BlobCache_StoreContentClient, error) {
	stream, err := c.cc.NewStream(ctx, &BlobCache_ServiceDesc.Streams[0], BlobCache_StoreContent_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &blobCacheStoreContentClient{stream}
	return x, nil
}

type BlobCache_StoreContentClient interface {
	Send(*StoreContentRequest) error
	CloseAndRecv() (*StoreContentResponse, error)
	grpc.ClientStream
}

type blobCacheStoreContentClient struct {
	grpc.ClientStream
}

func (x *blobCacheStoreContentClient) Send(m *StoreContentRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *blobCacheStoreContentClient) CloseAndRecv() (*StoreContentResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(StoreContentResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// BlobCacheServer is the server API for BlobCache service.
// All implementations must embed UnimplementedBlobCacheServer
// for forward compatibility
type BlobCacheServer interface {
	GetContent(context.Context, *GetContentRequest) (*GetContentResponse, error)
	StoreContent(BlobCache_StoreContentServer) error
	mustEmbedUnimplementedBlobCacheServer()
}

// UnimplementedBlobCacheServer must be embedded to have forward compatible implementations.
type UnimplementedBlobCacheServer struct {
}

func (UnimplementedBlobCacheServer) GetContent(context.Context, *GetContentRequest) (*GetContentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetContent not implemented")
}
func (UnimplementedBlobCacheServer) StoreContent(BlobCache_StoreContentServer) error {
	return status.Errorf(codes.Unimplemented, "method StoreContent not implemented")
}
func (UnimplementedBlobCacheServer) mustEmbedUnimplementedBlobCacheServer() {}

// UnsafeBlobCacheServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BlobCacheServer will
// result in compilation errors.
type UnsafeBlobCacheServer interface {
	mustEmbedUnimplementedBlobCacheServer()
}

func RegisterBlobCacheServer(s grpc.ServiceRegistrar, srv BlobCacheServer) {
	s.RegisterService(&BlobCache_ServiceDesc, srv)
}

func _BlobCache_GetContent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetContentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlobCacheServer).GetContent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BlobCache_GetContent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlobCacheServer).GetContent(ctx, req.(*GetContentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BlobCache_StoreContent_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(BlobCacheServer).StoreContent(&blobCacheStoreContentServer{stream})
}

type BlobCache_StoreContentServer interface {
	SendAndClose(*StoreContentResponse) error
	Recv() (*StoreContentRequest, error)
	grpc.ServerStream
}

type blobCacheStoreContentServer struct {
	grpc.ServerStream
}

func (x *blobCacheStoreContentServer) SendAndClose(m *StoreContentResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *blobCacheStoreContentServer) Recv() (*StoreContentRequest, error) {
	m := new(StoreContentRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// BlobCache_ServiceDesc is the grpc.ServiceDesc for BlobCache service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BlobCache_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "blobcache.BlobCache",
	HandlerType: (*BlobCacheServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetContent",
			Handler:    _BlobCache_GetContent_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StoreContent",
			Handler:       _BlobCache_StoreContent_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "blobcache.proto",
}
